---
title: "Uncertainty examples with ARIMA in brms"
output:
  github_document:
    toc: true
---

## Setup

```{r setup, message = FALSE, warning = FALSE}
library(tidyverse)
library(ggplot2)
library(rstan)
library(modelr)
library(tidybayes)
library(brms)
library(gganimate)

theme_set(theme_light() + theme(
  panel.border = element_blank()
))
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
```

## Data

We'll use example data based on [this brms issue](https://github.com/paul-buerkner/brms/issues/398)

```{r}
set.seed(250)
t_drift = arima.sim(list(order = c(1,0,0), ar = 0.8), n = 50) + 0.50 * seq(1,50)
t_drift_df = data_frame(
  time = seq_along(t_drift),
  y = as.vector(t_drift)
)
```

Which looks like:

```{r}
t_drift_df %>%
  ggplot(aes(x = time, y = y)) +
  geom_point()
```

## Model

A simple autoregressive model in brms:

```{r}
m <- brm(y ~ 1 + time, autocor = cor_ar(~ 1, p = 1), data = t_drift_df)
```

## Spaghetti plot

We'll start with a spaghetti plot:

```{r}
t_drift_df %>%
  add_predicted_draws(m, n = 100) %>%
  ggplot(aes(x = time, y = .prediction)) +
  geom_line(aes(group = .draw), alpha = 1/20) +
  geom_point(aes(y = y), data = t_drift_df)
```

We can add forecasting:

```{r}
t_drift_df %>%
  bind_rows(data_frame(time = (max(.$time) + 1):(max(.$time + 1) + 10))) %>%
  add_predicted_draws(m, n = 100) %>%
  ggplot(aes(x = time, y = .prediction)) +
  geom_line(aes(group = .draw), alpha = 1/20) +
  geom_point(aes(y = y), data = t_drift_df)
```

And finally, animation:

```{r}
ndraws = 100

p = t_drift_df %>%
  bind_rows(data_frame(time = max(.$time + 1):max(.$time + 10))) %>%
  add_predicted_draws(m, n = ndraws) %>%
  ggplot(aes(x = time, y = .prediction)) +
  geom_line(aes(group = .draw), color = "red") +
  geom_point(aes(y = y), data = t_drift_df) +
  transition_states(.draw, 1, 3) +
  shadow_mark(future = TRUE, color = "gray50", alpha = 1/20) +
  exit_recolor(color = "gray97") +
  enter_recolor(color = "gray97")

animate(p, nframes = ndraws * 5, fps = 10, width = 600, height = 400, res = 100, type = "cairo")
```
